# config.yaml

# **Mandatory Configuration**

# Base URL for your Overseerr instance (e.g., "http://localhost:5055")
OVERSEERR_BASEURL: "http://127.0.0.1:5055"

# Set to 'true' to enable dry run mode (no changes will be made), 'false' to apply changes
DRY_RUN: false

# API keys for accessing Overseerr and other services
API_KEYS:
  # **Mandatory**: Overseerr API key (replace with your actual API key)
  overseerr: "YOUR_OVERSEERR_API_KEY"

# **TV Show Categories**
TV_CATEGORIES:

  # **Default Category**
  default: "GeneralTV"

  # **Example Category for TV Shows**
  GeneralTV:
    # **Mandatory**: 'apply' section with required fields
    apply:
      # **Mandatory**: Root folder where TV shows will be stored
      root_folder: "/path/to/your/tv/shows"

      # **Mandatory**: The default quality profile ID to use
      default_profile_id: 1

      # **Mandatory**: The Sonarr server ID (as configured in Overseerr)
      sonarr_id: 0

      # **Optional**: Friendly name for logging purposes
      app_name: "General TV Shows"

      # **Optional**: Quality profile rules to override the default profile
      # quality_profile_rules:
      #   - priority: 1
      #     condition:
      #       release_year:
      #         "<": 2010
      #     profile_id: 2

    # **Mandatory**: Weight to determine category priority (higher means higher priority)
    weight: 10

    # **Optional**: Filters to match specific TV shows
    # If no filters are specified, this category matches all TV shows
    # filters:
    #   genres:
    #     - "Drama"
    #   keywords:
    #     - "action"

  # **Another Example Category for TV Shows**
  KidsTV:
    apply:
      root_folder: "/path/to/your/kids/tv/shows"
      default_profile_id: 3
      sonarr_id: 0
      app_name: "Kids TV Shows"
    weight: 100
    filters:
      genres:
        - "Animation"
        - "Family"
      # **Optional**: Exclude TV shows with certain age ratings
      excluded_ratings:
        - "TV-MA"

# **Movie Categories**
MOVIE_CATEGORIES:

  # **Default Category**
  default: "GeneralMovies"

  # **Example Category for Movies**
  GeneralMovies:
    apply:
      root_folder: "/path/to/your/movies"
      default_profile_id: 1
      radarr_id: 0
      app_name: "General Movies"
    weight: 10
    # No filters means this category matches all movies

  # **Another Example Category for Movies**
  FamilyMovies:
    apply:
      root_folder: "/path/to/your/family/movies"
      default_profile_id: 4
      radarr_id: 0
      app_name: "Family Movies"
    weight: 100
    filters:
      genres:
        - "Family"
        - "Animation"
      excluded_ratings:
        - "R"
        - "NC-17"

# End of config.yaml