# The URL of your Overseerr instance
OVERSEERR_BASEURL: "http://127.0.0.1:5055"

# If true, OverFiltrr logs actions but does not update/approve requests
DRY_RUN: false

# Control whether OverFiltrr auto-approves requests after updating them
# true  = update + approve (default)
# false = update only (leave Pending Approval)
ALLOW_AUTO_APPROVE: true

# Optional: secure the /webhook endpoint with a static token.
# If TOKEN is set (non-empty), clients must send header: X-Webhook-Token: <TOKEN>
WEBHOOK:
  TOKEN: ""  # e.g., "a-long-random-string"; leave empty to disable token check

# API Keys
API_KEYS:
  overseerr: "YOUR_OVERSEERR_API_KEY_HERE"

# Server configuration for the webhook listener (optional)
SERVER:
  HOST: "0.0.0.0"      # Host to bind the server to
  PORT: 12210           # Port to listen on
  THREADS: 15           # Number of worker threads
  CONNECTION_LIMIT: 500 # Maximum number of simultaneous connections

# Notifiarr (Optional)
# Used to post a rich Discord message via Notifiarr's passthrough API
NOTIFIARR:
  API_KEY: "YOUR_NOTIFIARR_KEY_HERE"
  CHANNEL: 123456789012345678
  # SOURCE is optional; defaults to "Overseerr" if not set in config
  SOURCE: "OverFiltrr"
  # Timeout in seconds for Notifiarr API request
  TIMEOUT: 10

# TV_CATEGORIES
#   - Defines how TV requests (Sonarr) are categorized.
#   - 'default' is a fallback category if no other matches.
TV_CATEGORIES:

  # -- Category 1: Anime (uses deterministic anime gate when is_anime: true)
  Anime:
    is_anime: true
    filters:
      # Simple cues that can add score towards this category
      keywords: ["anime"]
      genres: ["Animation"]
    # Rating helper:
    # - ceiling: block if final rating is stricter than this
    # - prefer: add a small positive weight if <= this rating
    ratings:
      ceiling: "R"
      prefer: "PG-13"
    apply:
      root_folder: "/mnt/media/sonarr/Anime"
      default_profile_id: 10
      sonarr_id: 3
      app_name: "Anime TV"
    weight: 100
    quality_profile_rules:
      - priority: 1
        condition:
          original_language: { "==": "ja" }
        profile_id: 12
      - priority: 2
        condition:
          networks: { "in": ["Netflix"] }
        profile_id: 13

  # -- Category 2: English TV
  English:
    # Broad catch-all with a permissive rating ceiling
    ratings:
      ceiling: "NC-17"
    apply:
      root_folder: "/mnt/media/sonarr/English"
      default_profile_id: 21
      sonarr_id: 2
      app_name: "English TV"
    weight: 50
    quality_profile_rules:
      - priority: 1
        condition:
          release_year: { "<": 2005 }
          original_language: { "!=": "en" }
        logic: "AND"
        profile_id: 30
      - priority: 2
        condition:
          release_year: { "<": 1980 }
        profile_id: 31
      - priority: 3
        condition:
          networks: { "in": ["Netflix"] }
        profile_id: 32

  # -- Category 3: Foreign TV
  Foreign:
    filters:
      keywords: ["foreign"]
      genres: ["Foreign"]
    apply:
      root_folder: "/mnt/media/sonarr/Foreign"
      default_profile_id: 22
      sonarr_id: 4
      app_name: "Foreign TV"
    weight: 70

  # If no other categories match, fall back here
  default: "English"


# 6) MOVIE_CATEGORIES
#    - Same concept as TV, but for Radarr.

MOVIE_CATEGORIES:

  # -- Category 1: KidMovies
  KidMovies:
    filters:
      genres: ["Animation", "Family"]
      keywords: ["kids", "child", "animated"]
    ratings:
      ceiling: "PG-13"
    apply:
      root_folder: "/mnt/media/radarr/KidMovies"
      default_profile_id: 15
      radarr_id: 1
      app_name: "Kid Movies"
    weight: 80
    quality_profile_rules:
      - priority: 1
        condition:
          providers: { "in": ["Netflix"] }
        profile_id: 16
      - priority: 2
        condition:
          release_year: { "<": 2000 }
          original_language: { "!=": "en" }
        logic: "AND"
        profile_id: 17

  # -- Category 2: Action
  Action:
    filters:
      genres: ["Action"]
    ratings:
      ceiling: "NC-17"
    apply:
      root_folder: "/mnt/media/radarr/Action"
      default_profile_id: 20
      radarr_id: 2
      app_name: "Action Movies"
    weight: 60
    quality_profile_rules:
      - priority: 1
        condition:
          production_companies: { "in": ["Marvel Studios", "Disney"] }
        profile_id: 25
      - priority: 2
        condition:
          release_year: { ">=": 2020 }
          keywords: { "in": ["superhero", "dc comics"] }
        profile_id: 26

  # -- Category 3: EverythingElse
  EverythingElse:
    apply:
      root_folder: "/mnt/media/radarr/Everything"
      default_profile_id: 10
      radarr_id: 3
      app_name: "General Movies"
    weight: 10
    quality_profile_rules:
      - priority: 1
        condition:
          status: { "==": "Released" }
        profile_id: 11
      - priority: 2
        condition:
          release_year: { "<": 1990 }
        profile_id: 12

  # Default fallback if no filters match
  default: "EverythingElse"
