LOG_LEVEL: "INFO"
LOGGING:
  MAX_BYTES: 1024
  BACKUP_COUNT: 1
OVERSEERR_BASEURL: "http://localhost:5055"
DRY_RUN: True
API_KEYS:
  overseerr: "your_overseerr_api_key"
  # other app API keys

TV_CATEGORIES:
  default: "standard_tv"
  anime_tv:
    weight: 1
    # Missing quality_profile_rules and default_profile_id - this should cause an error
    apply:
      root_folder: "/tv/Anime/"
      sonarr_id: 1
      app_name: "Sonarr Anime"
    filters:
      genres: ["Animation", "Anime"]
  standard_tv:
    weight: 0
    quality_profile_rules:
      - priority: 1
        profile_id: 1
        condition:
          release_year: { ">=": 2020 }
    apply:
      root_folder: "/tv/Standard/"
      sonarr_id: 2
      app_name: "Sonarr Standard"
      default_profile_id: 1 # Present here, but quality_profile_rules is also present

MOVIE_CATEGORIES:
  default: "standard_movies"
  action_movies:
    weight: 1
    quality_profile_rules: [] # Empty quality_profile_rules, missing default_profile_id - this should also cause an error
    apply:
      root_folder: "/movies/Action/"
      radarr_id: 1
      app_name: "Radarr Action"
    filters:
      genres: ["Action"]
  standard_movies:
    weight: 0
    apply:
      root_folder: "/movies/Standard/"
      radarr_id: 2
      app_name: "Radarr Standard"
      default_profile_id: 2 # default_profile_id is present, quality_profile_rules is missing (None) - this is okay
NOTIFIARR:
  API_KEY: "your_notifiarr_api_key"
  CHANNEL: "your_notifiarr_channel_id"
  SOURCE: "OverFiltrr Test"
